/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.GestionDatos;
import java.awt.Color;
import clases.GestionUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author ediso
 */
public class IniciarSesion extends javax.swing.JFrame  {
    
    private GestionUsuarios gestionUsuarios;

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        GestionDatos.cargarDatos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jPasswordFieldClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextFieldCorreo.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCorreo.setText("Ingrese su correo");
        jTextFieldCorreo.setBorder(null);
        jTextFieldCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCorreoMousePressed(evt);
            }
        });
        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });

        jLabel1.setText("CORREO");

        jLabel2.setText("CLAVE");

        jButtonEntrar.setText("ENTRAR");
        jButtonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jLabel3.setText("¿No estas registrado?");

        jButtonRegistrarse.setText("Registrate");
        jButtonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });

        jPasswordFieldClave.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldClave.setText("********");
        jPasswordFieldClave.setBorder(null);
        jPasswordFieldClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldClaveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRegistrarse))
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldClave)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonRegistrarse))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCorreoMousePressed
        // TODO add your handling code here:
        if (jTextFieldCorreo.getText().equals("Ingrese su correo")) {
            jTextFieldCorreo.setText("");
            jTextFieldCorreo.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordFieldClave.getPassword()).isEmpty()) {
            jPasswordFieldClave.setText("********");
            jPasswordFieldClave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldCorreoMousePressed

    private void jPasswordFieldClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordFieldClave.getPassword()).equals("********")) {
            jPasswordFieldClave.setText("");
            jPasswordFieldClave.setForeground(Color.black);
        }
        if (jTextFieldCorreo.getText().isEmpty()) {
            jTextFieldCorreo.setText("Ingrese su correo");
            jTextFieldCorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordFieldClaveMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GestionDatos.guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        // TODO add your handling code here:
        Registrarse nuevoRFrame = new Registrarse(this);
        this.setVisible(false);
        nuevoRFrame.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed
    
    public class ExcepcionIniciarSesion extends Exception {
        public ExcepcionIniciarSesion(String mensaje) {
        super(mensaje);
        }
    }
    
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        try{
            if ((!gestionUsuarios.getNombres().contains(jTextFieldCorreo.getText())) && (!gestionUsuarios.getClaves().contains(jPasswordFieldClave))){
                throw new ExcepcionIniciarSesion("Usuario no encontrado");
            }
            else {
              PedirComida nuevoPCFrame = new PedirComida();
                this.setVisible(false);
                nuevoPCFrame.setVisible(true);  
            }
            
        } 
        catch (ExcepcionIniciarSesion eis){
            JOptionPane.showMessageDialog(this, eis.getMessage(), "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed
    
   
  
    
    
    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JTextField jTextFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
